import { Link } from "react-router-dom";
import { Content } from "../components/Content";
import { Nav } from "../components/Nav";
import { routes } from "../router";
import proofIcon from "../assets/proof.svg"
import { API_ENDPOINTS, API_REQ_ERR_TIMEOUT_MS, verifyPreidction, downloadFile } from "../api";
import { useState } from "react";
import { RequestStatus } from "../types";

export const Verify = () => {

  const [reqStatus, setReqStatus] = useState<RequestStatus>('init')
  const [msg, setMsg] = useState<string>("")
  // input files
  const [proof, setProof] = useState<File | null>(null)
  const [vk, setVk] = useState<File | null>(null)
  const [srs, setSrs] = useState<File | null>(null)

  const handleFileChange = (event: React.ChangeEvent<HTMLInputElement>, ext?: string): File | void => {
    if (!event.target.files) return
    const file = event.target.files[0]
    if (!file) return
    if (ext) {
      if (!file.name.endsWith(ext)) return
    }
    return file
  }

  const handleVerifyPrediction = async () => {
    if (!proof) return
    setReqStatus('loading')
    const verified = await verifyPreidction(proof, vk, srs, () => {
      setReqStatus('error')
      setTimeout(() => setReqStatus('init'), API_REQ_ERR_TIMEOUT_MS)
    })
    if (!verified) {
      setReqStatus('ready')
      return setMsg("Looks like the proof file was not generated by our Model")
    }
    setReqStatus('success')
    setMsg("Verification OK. This proof was generated by our Model")
  }

  return (
    <Content>
      <Nav title={routes.verify.title} />
      <div className="flex flex-col gap-3 items-center">
        <ul className="list-decimal">
          <li>
            Go to the&nbsp;
            <Link to={routes.records.path}>Records page</Link>
          </li>
          <li className="leading-6">
            <div className="flex gap-0.5">
              Grab the Proof of Computation by clicking the
              <img
                draggable={false}
                className="flex w-6 h-6"
                src={proofIcon}
                alt="proof-icon"
                title="Download proof of computation"
              />
              icon
            </div>
          </li>
          <li>
            You can also download the Verifier Key (VK)&nbsp;
            <Link to={""} onClick={() => downloadFile(API_ENDPOINTS.GET_VK)}>here</Link>
            &nbsp;and the SRS file&nbsp;
            <Link to={""} onClick={() => downloadFile(API_ENDPOINTS.GET_SRS)}>here</Link>
            .
          </li>
          <li>Attach the files and verify if your prediction was computed by our Model</li>
          <p className="font-semibold">The VK and SRS you download here should match the&nbsp;
            <Link target={"_blank"} to={"https://github.com/teavver/zkml-web/tree/main/backend"}>codebase files</Link>
            .
          </p>
        </ul>

        <div className="flex flex-col gap-1 items-center">
          <div className="flex gap-1">
            <span>Proof:</span>
            <input
              type="file"
              name="verify-input-proof"
              accept=".pf"
              onChange={(e) => {
                const file = handleFileChange(e, ".pf")
                if (!file) return
                setProof(file)
              }}
            />
          </div>
          <div className="flex gap-1">
            <span>VK*:</span>
            <input
              type="file"
              name="verify-input-vk"
              accept=".vk"
              onChange={(e) => {
                const file = handleFileChange(e, ".vk")
                if (!file) return
                setVk(file)
              }}
            />
          </div>
          <div className="flex gap-1">
            <span>SRS*:</span>
            <input
              type="file"
              name="verify-input-srs"
              onChange={(e) => {
                const file = handleFileChange(e)
                if (!file) return
                setSrs(file)
              }}
            />
          </div>
          <p>* = Optional</p>

          <div className="my-2">
            <button disabled={proof === null} onClick={handleVerifyPrediction}>Verify</button>
          </div>
        </div>

        {(reqStatus !== 'init' && msg === "") &&
          <div>
            <p>{reqStatus}</p>
          </div>
        }

        {msg !== "" &&
          <p>{msg}</p>
        }

      </div>
    </Content>
  )
}